[ubuntu_servers]
vm1 ansible_host=192.168.1.135
vm2 ansible_host=192.168.1.69
vm3 ansible_host=192.168.1.28
vm4 ansible_host=192.168.1.77
vm5 ansible_host=192.168.1.134

[ubuntu_servers:vars]
ansible_user=calvin
ansible_become=true
ansible_become=true
ansible_become_method=sudo
