[ubuntu_servers]
geonode_proj     ansible_host=192.168.1.132
code_server     ansible_host=192.168.1.69
postgresql_prd  ansible_host=192.168.1.28
webserver_prd   ansible_host=192.168.1.77
geonode_prd     ansible_host=192.168.1.134
jenkins         ansible_host=192.168.1.79
jenkins_agent   ansible_host=192.168.1.80
harbor_registry ansible_host=192.168.1.45

[ubuntu_servers:vars]
ansible_user=calvin
ansible_become=true
ansible_become_method=sudo
