[ubuntu_servers]
vm1 ansible_host=192.168.1.135
vm2 ansible_host=192.168.1.69

[ubuntu_servers:vars]
ansible_user=automation
ansible_become=true
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_become=true
ansible_become_method=sudo
